# Generated by Django 3.2.4 on 2021-06-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True)),
                ('date_post', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('descrição', models.TextField(max_length=250)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ult_atua', models.DateTimeField(auto_now=True)),
                ('quantidade', models.IntegerField()),
                ('estoque', models.BooleanField(default=True)),
                ('image', models.URLField()),
            ],
        ),
    ]
