# Generated by Django 3.1.3 on 2021-07-07 06:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_qtd'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='nome', unique=True),
        ),
    ]
