# Generated by Django 3.2.4 on 2021-06-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20210614_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
