# Generated by Django 3.2.4 on 2021-06-14 16:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produtos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
