# Generated by Django 3.2.4 on 2021-06-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produtos_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
