# Generated by Django 3.1.3 on 2021-07-07 06:28

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20210707_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='qtd',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True),
        ),
    ]
