# Generated by Django 3.2.4 on 2021-06-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_produtos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/image'),
        ),
    ]
