# Generated by Django 3.2.4 on 2021-06-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_produtos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='date_post',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='ult_atua',
            field=models.DateTimeField(),
        ),
    ]
